<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hidwizards.IOWrapper.Libraries.ProviderLogger</RootNamespace>
    <AssemblyName>IOWrapper.Libraries.ProviderLogger</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataObjects\DTOs.csproj" />
  </ItemGroup>

</Project>
