<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Core_ViGEm</RootNamespace>
    <AssemblyName>Core_ViGEm</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\DataObjects\DTOs.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\ProviderLogger\ProviderLogger.csproj" />
    <ProjectReference Include="..\..\ProviderInterface\ProviderInterface.csproj" />
  </ItemGroup>

</Project>
