<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Core_Interception</RootNamespace>
    <AssemblyName>Core_Interception</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataObjects\DTOs.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\Device Querying\DeviceLibrary\DeviceLibrary.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\Device Querying\HidDeviceHelper\HidDeviceHelper.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\Device Update Handling\DeviceHandlers\DeviceHandlers.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\ProviderLogger\ProviderLogger.csproj" />
    <ProjectReference Include="..\..\Provider Libraries\Subscription Handling\SubscriptionHandler\SubscriptionHandler.csproj" />
    <ProjectReference Include="..\..\ProviderInterface\ProviderInterface.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Settings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
