<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HidWizards.UCR.Plugins</RootNamespace>
    <AssemblyName>UCR.Plugins</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UCR.Core\UCR.Core.csproj" />
  </ItemGroup>

  <Target Name="CopyToPluginsFolder" AfterTargets="Build">
    <PropertyGroup>
      <UcrAppPluginsDir>$(MSBuildThisFileDirectory)..\UCR\bin\$(Configuration)\$(TargetFramework)\Plugins\$(TargetName)\</UcrAppPluginsDir>
    </PropertyGroup>
    <ItemGroup>
      <PluginOutputFiles Include="$(TargetDir)$(TargetName).dll" />
      <PluginOutputFiles Include="$(TargetDir)$(TargetName).pdb" Condition="'$(Configuration)' == 'Debug' AND Exists('$(TargetDir)$(TargetName).pdb')" />
    </ItemGroup>
    <MakeDir Directories="$(UcrAppPluginsDir)" Condition="!Exists('$(UcrAppPluginsDir)')" />
    <Copy SourceFiles="@(PluginOutputFiles)" DestinationFolder="$(UcrAppPluginsDir)" />
  </Target>

</Project>
