<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hidwizards.IOWrapper.Libraries.EmptyEventDictionary</RootNamespace>
    <AssemblyName>IOWrapper.Libraries.EmptyEventDictionary</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
