<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Hidra.IOWrapper.Libraries.SubscriptionHandlers</RootNamespace>
    <AssemblyName>Hidra.IOWrapper.Libraries.SubscriptionHandlers</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\DataObjects\DTOs.csproj" />
    <ProjectReference Include="..\EmptyEventDictionary\EmptyEventDictionary.csproj" />
  </ItemGroup>

</Project>
